const tailwindConfig = {
  content: [
    "./index.html",
    "./*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./context/**/*.{js,ts,jsx,tsx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "color-mix(in srgb, var(--color-background) calc(100% * <alpha-value>), transparent)",
        foreground: "color-mix(in srgb, var(--color-foreground) calc(100% * <alpha-value>), transparent)",
        ink: "color-mix(in srgb, var(--color-ink) calc(100% * <alpha-value>), transparent)",
        "ink-foreground": "color-mix(in srgb, var(--color-ink-foreground) calc(100% * <alpha-value>), transparent)",
        night: "color-mix(in srgb, var(--color-night) calc(100% * <alpha-value>), transparent)",
        "night-foreground": "color-mix(in srgb, var(--color-night-foreground) calc(100% * <alpha-value>), transparent)",
        panel: "color-mix(in srgb, var(--color-panel) calc(100% * <alpha-value>), transparent)",
        "panel-foreground": "color-mix(in srgb, var(--color-panel-foreground) calc(100% * <alpha-value>), transparent)",
        mist: "color-mix(in srgb, var(--color-mist) calc(100% * <alpha-value>), transparent)",
        "mist-foreground": "color-mix(in srgb, var(--color-mist-foreground) calc(100% * <alpha-value>), transparent)",
        primary: "color-mix(in srgb, var(--color-primary) calc(100% * <alpha-value>), transparent)",
        "primary-foreground": "color-mix(in srgb, var(--color-primary-foreground) calc(100% * <alpha-value>), transparent)",
        accent: "color-mix(in srgb, var(--color-accent) calc(100% * <alpha-value>), transparent)",
        "accent-foreground": "color-mix(in srgb, var(--color-accent-foreground) calc(100% * <alpha-value>), transparent)",
        ember: "color-mix(in srgb, var(--color-ember) calc(100% * <alpha-value>), transparent)",
        "ember-foreground": "color-mix(in srgb, var(--color-ember-foreground) calc(100% * <alpha-value>), transparent)",
        lavender: "color-mix(in srgb, var(--color-lavender) calc(100% * <alpha-value>), transparent)",
        "lavender-foreground": "color-mix(in srgb, var(--color-lavender-foreground) calc(100% * <alpha-value>), transparent)",
        lilac: "color-mix(in srgb, var(--color-lilac) calc(100% * <alpha-value>), transparent)",
        "lilac-foreground": "color-mix(in srgb, var(--color-lilac-foreground) calc(100% * <alpha-value>), transparent)",
        slate: "color-mix(in srgb, var(--color-slate) calc(100% * <alpha-value>), transparent)",
        "slate-foreground": "color-mix(in srgb, var(--color-slate-foreground) calc(100% * <alpha-value>), transparent)",
        line: "color-mix(in srgb, var(--color-line) calc(100% * <alpha-value>), transparent)",
        "line-foreground": "color-mix(in srgb, var(--color-line-foreground) calc(100% * <alpha-value>), transparent)",
        hairline: "color-mix(in srgb, var(--color-hairline) calc(100% * <alpha-value>), transparent)",
        "hairline-foreground": "color-mix(in srgb, var(--color-hairline-foreground) calc(100% * <alpha-value>), transparent)",
        success: "color-mix(in srgb, var(--color-success) calc(100% * <alpha-value>), transparent)",
        "success-foreground": "color-mix(in srgb, var(--color-success-foreground) calc(100% * <alpha-value>), transparent)",
        danger: "color-mix(in srgb, var(--color-danger) calc(100% * <alpha-value>), transparent)",
        "danger-foreground": "color-mix(in srgb, var(--color-danger-foreground) calc(100% * <alpha-value>), transparent)",
      },
      fontFamily: {
        heading: ["var(--font-heading)"],
        sans: ["var(--font-sans)"],
        quran: ["var(--font-quran)"],
      },
      spacing: {
        "section-spacing": "var(--spacing-section)",
        "section-spacing-mobile": "var(--spacing-section-mobile)",
        gutter: "var(--spacing-gutter)",
        "gutter-lg": "var(--spacing-gutter-lg)",
        block: "var(--spacing-block)",
        stack: "var(--spacing-stack)",
        tight: "var(--spacing-tight)",
      },
      borderRadius: {
        pill: "var(--radius-pill)",
        card: "var(--radius-card)",
        panel: "var(--radius-panel)",
        control: "var(--radius-control)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        base: "var(--duration-base)",
        slow: "var(--duration-slow)",
      },
      scale: {
        hover: "var(--scale-hover)",
        active: "var(--scale-active)",
      },
      translate: {
        "hover-lift": "var(--lift-hover)",
      },
      maxWidth: {
        shell: "88rem",
        prose: "42rem",
      },
    },
  },
};

export default tailwindConfig;